version: "3.5"

services:
  rabbitmq:
    build: ./rabbitmq

    hostname: rabbitmq

    expose:
      - "5672" # Rabbitmq port

    ports:
      - "15672:15672"
      - "5672:5672"

  udp_bridge_listen:
    build: ./python3

    network_mode: host

    environment:
      RABBITMQ_HOST: localhost

    restart: on-failure

    depends_on:
      - rabbitmq

    volumes:
      - ../:/app

    command: "python3 -m modules.udp_bridge -p udp_listen -c conf/udp_bridge_gcs.yaml"

  udp_bridge_broadcast:
    build: ./python3

    network_mode: host

    environment:
      RABBITMQ_HOST: localhost

    restart: on-failure

    depends_on:
      - rabbitmq

    volumes:
      - ../:/app

    command: "python3 -m modules.udp_bridge -p udp_broadcast -c conf/udp_bridge_gcs.yaml"

  server:
    build: ./python3

    environment:
      RABBITMQ_HOST: rabbitmq

    expose:
      - "5672"

    ports:
      - "0.0.0.0:80:5000" # Web app

    volumes:
      - ../:/app

    command: "python3 -m server.server -c conf/server.yaml"
